// <auto-generated />
using System;
using Hogwarts.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hogwarts.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210628142304_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("Hogwarts.Data.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlantelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlantelId");

                    b.ToTable("Departamentos");

                    b.HasData(
                        new
                        {
                            Id = 1301,
                            Nombre = "Departamento Software",
                            PlantelId = 501
                        },
                        new
                        {
                            Id = 1302,
                            Nombre = "Departamento Diseño",
                            PlantelId = 501
                        },
                        new
                        {
                            Id = 1401,
                            Nombre = "Departamento Computo",
                            PlantelId = 601
                        },
                        new
                        {
                            Id = 1402,
                            Nombre = "Departamento Ingenierías",
                            PlantelId = 601
                        },
                        new
                        {
                            Id = 1501,
                            Nombre = "Departamento Pruebas",
                            PlantelId = 701
                        },
                        new
                        {
                            Id = 1502,
                            Nombre = "Departamento Administracion",
                            PlantelId = 701
                        });
                });

            modelBuilder.Entity("Hogwarts.Data.PermisoCumpleano", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PermisoCumpleanos");
                });

            modelBuilder.Entity("Hogwarts.Data.PermisoEconomico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaFinal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PermisoEconomicos");
                });

            modelBuilder.Entity("Hogwarts.Data.PermisoHora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Horario")
                        .HasColumnType("TEXT");

                    b.Property<string>("Motivo")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PermisoHoras");
                });

            modelBuilder.Entity("Hogwarts.Data.Plantel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Planteles");

                    b.HasData(
                        new
                        {
                            Id = 501,
                            Nombre = "Plantel Zapopan"
                        },
                        new
                        {
                            Id = 601,
                            Nombre = "Plantel Tlaquepaque"
                        },
                        new
                        {
                            Id = 701,
                            Nombre = "Plantel Guadalajara"
                        });
                });

            modelBuilder.Entity("Hogwarts.Data.TipoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TipoUsuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Tipo = "Jefe"
                        },
                        new
                        {
                            Id = 2,
                            Tipo = "Empleado"
                        });
                });

            modelBuilder.Entity("Hogwarts.Data.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contrasena")
                        .HasColumnType("TEXT");

                    b.Property<string>("Correo")
                        .HasColumnType("TEXT");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimerNombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("SegundoNombre")
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoUsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("TipoUsuarioId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 3312,
                            Contrasena = "3312",
                            Correo = "alex1123nel@gmail.com",
                            DepartamentoId = 1301,
                            FechaIngreso = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2014),
                            FechaNacimiento = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1973),
                            PrimerNombre = "Vicente",
                            SegundoNombre = "Gonzalez Rueda",
                            TipoUsuarioId = 1
                        },
                        new
                        {
                            Id = 3313,
                            Contrasena = "3312",
                            Correo = "teresitaCS@howarts.com",
                            DepartamentoId = 1302,
                            FechaIngreso = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2015),
                            FechaNacimiento = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1958),
                            PrimerNombre = "Teresita",
                            SegundoNombre = "Barajas Sainz",
                            TipoUsuarioId = 1
                        },
                        new
                        {
                            Id = 3314,
                            Contrasena = "3312",
                            Correo = "AndresSS@howarts.com",
                            DepartamentoId = 1401,
                            FechaIngreso = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2012),
                            FechaNacimiento = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1966),
                            PrimerNombre = "Andres",
                            SegundoNombre = "Salamanca Sol",
                            TipoUsuarioId = 1
                        },
                        new
                        {
                            Id = 3315,
                            Contrasena = "3312",
                            Correo = "GraciaZA@howarts.com",
                            DepartamentoId = 1402,
                            FechaIngreso = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1995),
                            FechaNacimiento = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1971),
                            PrimerNombre = "Gracia",
                            SegundoNombre = "Zurita Armengol",
                            TipoUsuarioId = 1
                        },
                        new
                        {
                            Id = 3316,
                            Contrasena = "3312",
                            Correo = "DelgfinaAA@gmail.com",
                            DepartamentoId = 1501,
                            FechaIngreso = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1997),
                            FechaNacimiento = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1968),
                            PrimerNombre = "Delfina",
                            SegundoNombre = "Almeida Azorin",
                            TipoUsuarioId = 1
                        },
                        new
                        {
                            Id = 3317,
                            Contrasena = "3312",
                            Correo = "RamonaGC@howarts.com",
                            DepartamentoId = 1502,
                            FechaIngreso = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1985),
                            FechaNacimiento = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1967),
                            PrimerNombre = "Ramona",
                            SegundoNombre = "González Carrazco",
                            TipoUsuarioId = 1
                        },
                        new
                        {
                            Id = 3318,
                            Contrasena = "3312",
                            Correo = "EligioHD@howarts.com",
                            DepartamentoId = 1301,
                            FechaIngreso = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1997),
                            FechaNacimiento = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1951),
                            PrimerNombre = "Eligio",
                            SegundoNombre = "Hernandez Cadenas",
                            TipoUsuarioId = 2
                        },
                        new
                        {
                            Id = 3319,
                            Contrasena = "3312",
                            Correo = "RufinaBB@howarts.com",
                            DepartamentoId = 1301,
                            FechaIngreso = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1986),
                            FechaNacimiento = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1951),
                            PrimerNombre = "Rufina",
                            SegundoNombre = "Baró Bravo",
                            TipoUsuarioId = 2
                        },
                        new
                        {
                            Id = 3320,
                            Contrasena = "3312",
                            Correo = "RafaelBC@howarts.com",
                            DepartamentoId = 1301,
                            FechaIngreso = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1975),
                            FechaNacimiento = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1981),
                            PrimerNombre = "Rafael",
                            SegundoNombre = "Batlle Carreras",
                            TipoUsuarioId = 2
                        },
                        new
                        {
                            Id = 3321,
                            Contrasena = "3312",
                            Correo = "GonzaloMT@howarts.com",
                            DepartamentoId = 1302,
                            FechaIngreso = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1980),
                            FechaNacimiento = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1968),
                            PrimerNombre = "Gonzalo",
                            SegundoNombre = "Morillo Torres",
                            TipoUsuarioId = 2
                        },
                        new
                        {
                            Id = 3322,
                            Contrasena = "3312",
                            Correo = "AlejandraGD@howarts.com",
                            DepartamentoId = 1302,
                            FechaIngreso = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1979),
                            FechaNacimiento = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1969),
                            PrimerNombre = "Alejandra",
                            SegundoNombre = "Garcia Ayllon",
                            TipoUsuarioId = 2
                        },
                        new
                        {
                            Id = 3323,
                            Contrasena = "3312",
                            Correo = "CarinaCCE@howarts.com",
                            DepartamentoId = 1302,
                            FechaIngreso = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2013),
                            FechaNacimiento = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1945),
                            PrimerNombre = "Carina",
                            SegundoNombre = "Cabrera Enriquez",
                            TipoUsuarioId = 2
                        });
                });

            modelBuilder.Entity("Hogwarts.Data.Departamento", b =>
                {
                    b.HasOne("Hogwarts.Data.Plantel", null)
                        .WithMany("Departamentos")
                        .HasForeignKey("PlantelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hogwarts.Data.PermisoCumpleano", b =>
                {
                    b.HasOne("Hogwarts.Data.Usuario", null)
                        .WithMany("PermisoCumpleanos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hogwarts.Data.PermisoEconomico", b =>
                {
                    b.HasOne("Hogwarts.Data.Usuario", null)
                        .WithMany("PermisoEconomicos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hogwarts.Data.PermisoHora", b =>
                {
                    b.HasOne("Hogwarts.Data.Usuario", null)
                        .WithMany("PermisoHoras")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hogwarts.Data.Usuario", b =>
                {
                    b.HasOne("Hogwarts.Data.Departamento", null)
                        .WithMany("Usuarios")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hogwarts.Data.TipoUsuario", null)
                        .WithMany("Usuarios")
                        .HasForeignKey("TipoUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hogwarts.Data.Departamento", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Hogwarts.Data.Plantel", b =>
                {
                    b.Navigation("Departamentos");
                });

            modelBuilder.Entity("Hogwarts.Data.TipoUsuario", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Hogwarts.Data.Usuario", b =>
                {
                    b.Navigation("PermisoCumpleanos");

                    b.Navigation("PermisoEconomicos");

                    b.Navigation("PermisoHoras");
                });
#pragma warning restore 612, 618
        }
    }
}
